<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>JNPF 第三方登录整合库。</Description>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AlipaySDKNet.Standard" Version="4.6.442" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0" />
    <PackageReference Include="System.Xml.XmlDocument" Version="4.3.0" />
	<PackageReference Include="System.Xml.XPath.XmlDocument" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\modularity\common\JNPF.Common\JNPF.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TopSdk">
      <HintPath>Libraries\TopSdk.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
