namespace JNPF.InteAssistant.Codegen;

/// <summary>
/// .vm 模板 ID → sandbox 内相对路径（对齐 JNPF 命名空间约定）。
/// </summary>
public static class CodegenArtifactPaths
{
    public static string ToRelativePath(string templateId, string className) => templateId switch
    {
        VmTemplateIds.Entity => Path.Combine("Entitys", $"{className}Entity.cs"),
        VmTemplateIds.Service => Path.Combine("Services", $"{className}Service.cs"),
        VmTemplateIds.IService => Path.Combine("Interfaces", $"I{className}Service.cs"),
        _ => throw new ArgumentOutOfRangeException(nameof(templateId), $"未锁定的模板: {templateId}"),
    };

    public static string AutoGeneratedHeader(string sampleId, string templateId) =>
        $"// <auto-generated> sample={sampleId} template={templateId}{Environment.NewLine}";
}
