using JNPF.InteAssistant.Codegen.TemplateContext;
using JNPF.DependencyInjection;

namespace JNPF.InteAssistant.Codegen;

/// <summary>
/// 将渲染结果写入 workspace/generated/{tenant}/{project}/backend/ 并生成 sandbox csproj。
/// </summary>
public sealed class CodegenWorkspaceWriter : ITransient
{
    public string WriteSandbox(
        Ir2CodegenContext context,
        IReadOnlyDictionary<string, string> renderedByTemplateId,
        string? workspaceRoot = null)
    {
        workspaceRoot ??= Path.Combine(
            VmTemplateCatalog.ResolveRepoRoot(),
            "workspace",
            "generated",
            "_d3-gate",
            context.SampleId,
            "backend");

        if (Directory.Exists(workspaceRoot))
            Directory.Delete(workspaceRoot, recursive: true);

        WriteGenerated(workspaceRoot, context, renderedByTemplateId);
        return workspaceRoot;
    }

    /// <summary>
    /// 落盘通道 A/B 骨架（覆盖 .cs；保留已有 *.custom.cs）。
    /// </summary>
    public string WriteGenerated(
        string workspaceRoot,
        Ir2CodegenContext context,
        IReadOnlyDictionary<string, string> renderedByTemplateId)
    {
        Directory.CreateDirectory(workspaceRoot);

        foreach (var (templateId, content) in renderedByTemplateId)
        {
            var relative = CodegenArtifactPaths.ToRelativePath(templateId, context.ClassName);
            var fullPath = Path.Combine(workspaceRoot, relative);
            var dir = Path.GetDirectoryName(fullPath)!;
            Directory.CreateDirectory(dir);

            var header = CodegenArtifactPaths.AutoGeneratedHeader(context.SampleId, templateId);
            File.WriteAllText(fullPath, header + content, System.Text.Encoding.UTF8);
        }

        WriteDtoStubs(workspaceRoot, context);

        var csprojPath = Path.Combine(workspaceRoot, "JNPF.Codegen.Sandbox.csproj");
        File.WriteAllText(csprojPath, BuildCsprojContent(VmTemplateCatalog.ResolveRepoRoot()), System.Text.Encoding.UTF8);
        return workspaceRoot;
    }

    /// <summary>D3 sandbox 最小 Dto 占位，满足 Service.cs.vm 的 using；D4 起由 Dto .vm 替换。</summary>
    private static void WriteDtoStubs(string workspaceRoot, Ir2CodegenContext context)
    {
        var dtoDir = Path.Combine(workspaceRoot, "Entitys", "Dto", context.ClassName);
        Directory.CreateDirectory(dtoDir);
        var ns = $"JNPF.{context.NameSpace}.Entitys.Dto.{context.ClassName}";
        var stub = $$"""
// <auto-generated> D3 sandbox Dto stub — replaced by Dto .vm in D4+
namespace {{ns}};

public sealed class {{context.ClassName}}InfoOutput { }
public sealed class {{context.ClassName}}ListOutput { }
public sealed class {{context.ClassName}}CrInput { }
public sealed class {{context.ClassName}}UpInput { }
""";
        File.WriteAllText(Path.Combine(dtoDir, $"{context.ClassName}DtoStubs.cs"), stub, System.Text.Encoding.UTF8);
    }

    internal static string BuildCsprojContent(string repoRoot)
    {
        string Ref(string relativePath) =>
            Path.Combine(repoRoot, "backend", relativePath).Replace('\\', '/');

        var refs = new[]
        {
            Ref(@"framework/JNPF/JNPF.csproj"),
            Ref(@"framework/JNPF.Extras.DatabaseAccessor.SqlSugar/JNPF.Extras.DatabaseAccessor.SqlSugar.csproj"),
            Ref(@"modularity/common/JNPF.Common/JNPF.Common.csproj"),
            Ref(@"modularity/common/JNPF.Common.Core/JNPF.Common.Core.csproj"),
            Ref(@"modularity/common/JNPF.Common.CodeGen/JNPF.Common.CodeGen.csproj"),
            Ref(@"modularity/system/JNPF.Systems.Interfaces/JNPF.Systems.Interfaces.csproj"),
            Ref(@"modularity/system/JNPF.Systems/JNPF.Systems.csproj"),
            Ref(@"modularity/workflow/JNPF.WorkFlow.Entitys/JNPF.WorkFlow.Entitys.csproj"),
            Ref(@"modularity/engine/JNPF.Engine.Entity/JNPF.Engine.Entity.csproj"),
            Ref(@"modularity/engine/JNPF.VisualDev.Engine/JNPF.VisualDev.Engine.csproj"),
            Ref(@"modularity/visualdev/JNPF.VisualDev.Interfaces/JNPF.VisualDev.Interfaces.csproj"),
        };

        var refXml = string.Join(Environment.NewLine, refs.Select(r =>
            $"    <ProjectReference Include=\"{r}\" />"));

        return $$"""
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RootNamespace>JNPF.Codegen.Sandbox</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
{{refXml}}
  </ItemGroup>
</Project>
""";
    }
}
