using JNPF.InteAssistant.Codegen;
using JNPF.InteAssistant.Entitys.Dto.Ir;
using JNPF.InteAssistant.Entitys.Entity;
using JNPF.InteAssistant.Entitys.Ir;
using JNPF.InteAssistant.Ir;
using JNPF.InteAssistant.Skills;
using Microsoft.Extensions.Logging;

namespace JNPF.Tests.PhaseB;

/// <summary>
/// 阶段四 P4-B04a — ArchGuardService 读 yaml · AG-000～003 + Warning 透传。
/// </summary>
public static class IrPhase4ArchGuardTests
{
    public static async Task RunAllAsync()
    {
        TestRulesLoader_LoadsScanOrder();
        TestArchViolationPayload_Format();
        await TestAg000_ChannelCWriteForbiddenAsync();
        await TestAg001_DdlControllerReferenceAsync();
        await TestAg002_ServiceMissingTenantAsync();
        await TestAg003_SqlMissingTenantAsync();
        await TestLeaveSimple_GeneratedCodePassesCriticalAsync();
        Console.WriteLine("[Phase4] ArchGuard tests passed.");
    }

    private static void TestRulesLoader_LoadsScanOrder()
    {
        var rules = ArchGuardRulesLoader.GetOrderedRules();
        if (rules.Count < 7)
            throw new InvalidOperationException($"Expected >=7 rules, got {rules.Count}");

        if (rules[0].Id != "AG-000")
            throw new InvalidOperationException("Scan order must start with AG-000");
    }

    private static void TestArchViolationPayload_Format()
    {
        var result = new ArchGuardScanResult
        {
            Violations = new[]
            {
                new ArchGuardViolation
                {
                    RuleId = "AG-001",
                    Severity = "critical",
                    Message = "test",
                },
            },
        };

        var payload = ArchGuardManifestBuilder.BuildArchViolationPayload("proj-1", result);
        if (!payload.Contains("\"criticalCount\":1", StringComparison.Ordinal))
            throw new InvalidOperationException("ArchViolation payload missing criticalCount");
    }

    private static async Task TestAg000_ChannelCWriteForbiddenAsync()
    {
        const string tenantId = "_phase4-arch";
        const string projectId = "ag000-test";
        var backendRoot = PrepareBackend(tenantId, projectId);

        File.WriteAllText(
            Path.Combine(backendRoot, "Services", "RogueHelper.cs"),
            "// channel C write\npublic class RogueHelper { }");

        var service = CreateArchGuard();
        var result = service.Scan(tenantId, projectId);
        if (result.CriticalCount == 0 || result.Violations.All(v => v.RuleId != "AG-000"))
            throw new InvalidOperationException("AG-000 should detect rogue Services/*.cs");

        CleanupBackend(tenantId, projectId);
        await Task.CompletedTask;
    }

    private static async Task TestAg001_DdlControllerReferenceAsync()
    {
        const string tenantId = "_phase4-arch";
        const string projectId = "ag001-test";
        var backendRoot = PrepareBackend(tenantId, projectId);

        File.WriteAllText(
            Path.Combine(backendRoot, "Entitys", "BadEntity.cs"),
            "CREATE TABLE x REFERENCES dbo.LeaveController (id)");

        var snapshot = new IrSnapshot
        {
            Fragments = new[]
            {
                new IrSnapshotFragment
                {
                    FragmentId = "ddl:1",
                    FragmentType = IrFragmentTypes.DDL,
                    StabilityState = IrStabilityStates.Stable,
                    Payload = "{\"ddl\":\"FOREIGN KEY (x) REFERENCES LeaveController\"}",
                },
            },
        };

        var service = CreateArchGuard();
        var result = service.Scan(tenantId, projectId, snapshot);
        if (result.CriticalCount == 0 || result.Violations.All(v => v.RuleId != "AG-001"))
            throw new InvalidOperationException("AG-001 should detect Controller REFERENCES");

        CleanupBackend(tenantId, projectId);
        await Task.CompletedTask;
    }

    private static async Task TestAg002_ServiceMissingTenantAsync()
    {
        const string tenantId = "_phase4-arch";
        const string projectId = "ag002-test";
        var backendRoot = PrepareBackend(tenantId, projectId);

        File.WriteAllText(
            Path.Combine(backendRoot, "Services", "NoTenantService.cs"),
            "// <auto-generated>\npublic class NoTenantService { }");

        var service = CreateArchGuard();
        var result = service.Scan(tenantId, projectId);
        if (result.Violations.All(v => v.RuleId != "AG-002"))
            throw new InvalidOperationException("AG-002 should detect missing tenant patterns");

        CleanupBackend(tenantId, projectId);
        await Task.CompletedTask;
    }

    private static async Task TestAg003_SqlMissingTenantAsync()
    {
        const string tenantId = "_phase4-arch";
        const string projectId = "ag003-test";
        var backendRoot = PrepareBackend(tenantId, projectId);

        File.WriteAllText(
            Path.Combine(backendRoot, "Services", "SqlBadService.cs"),
            "class SqlBadService { void M() { Ado.SqlQuery(\"SELECT * FROM T\"); } }");

        var service = CreateArchGuard();
        var result = service.Scan(tenantId, projectId);
        if (result.Violations.All(v => v.RuleId != "AG-003"))
            throw new InvalidOperationException("AG-003 should detect SQL without tenant binding");

        CleanupBackend(tenantId, projectId);
        await Task.CompletedTask;
    }

    private static async Task TestLeaveSimple_GeneratedCodePassesCriticalAsync()
    {
        const string tenantId = "_phase4-arch";
        const string projectId = "leave-simple-arch";

        var backendRoot = CodegenWorkspacePaths.ResolveBackendRoot(tenantId, projectId);
        if (Directory.Exists(backendRoot))
            Directory.Delete(backendRoot, recursive: true);

        var devSkill = IrPhase4DeveloperTests.CreateDeveloperSkillPublic();
        var snapshot = IrPhase4DeveloperTests.BuildLeaveSimpleSnapshotPublic(includeSystemDesign: true);
        var context = new SkillContext
        {
            RunId = Guid.NewGuid().ToString("N"),
            TenantId = tenantId,
            ProjectId = projectId,
            PipelineId = 9003,
            UserRequirement = "请假 MVP arch",
            Snapshot = snapshot,
        };

        await foreach (var _ in devSkill.ReasonAsync(context))
        {
        }

        var archGuard = CreateArchGuard();
        var result = archGuard.Scan(tenantId, projectId, snapshot);
        if (!result.Passed)
        {
            var details = string.Join("; ", result.CriticalViolations.Select(v => $"{v.RuleId}:{v.Message}"));
            throw new InvalidOperationException($"leave-simple should pass critical arch rules: {details}");
        }

        CleanupBackend(tenantId, projectId);
    }

    private static string PrepareBackend(string tenantId, string projectId)
    {
        var backendRoot = CodegenWorkspacePaths.ResolveBackendRoot(tenantId, projectId);
        if (Directory.Exists(backendRoot))
            Directory.Delete(backendRoot, recursive: true);

        Directory.CreateDirectory(Path.Combine(backendRoot, "Services"));
        Directory.CreateDirectory(Path.Combine(backendRoot, "Entitys"));
        return backendRoot;
    }

    private static void CleanupBackend(string tenantId, string projectId)
    {
        var backendRoot = CodegenWorkspacePaths.ResolveBackendRoot(tenantId, projectId);
        if (Directory.Exists(backendRoot))
            Directory.Delete(backendRoot, recursive: true);
    }

    private static ArchGuardService CreateArchGuard()
    {
        using var loggerFactory = LoggerFactory.Create(static _ => { });
        return new ArchGuardService(
            new NoOpIrEventStore(),
            loggerFactory.CreateLogger<ArchGuardService>());
    }

    private sealed class NoOpIrEventStore : IIrEventStoreService
    {
        public Task<AiIrEventEntity> AppendAsync(
            string projectId,
            string tenantId,
            AppendIrEventRequest request,
            CancellationToken ct = default) =>
            Task.FromResult(new AiIrEventEntity { Id = Guid.NewGuid().ToString("N") });

        public Task<List<IrEventDto>> ListEventsAsync(
            string projectId, string tenantId, CancellationToken ct = default) =>
            Task.FromResult(new List<IrEventDto>());

        public Task<List<IrFragmentSnapshotDto>> ListSnapshotsAsync(
            string projectId, string tenantId, CancellationToken ct = default) =>
            Task.FromResult(new List<IrFragmentSnapshotDto>());

        public Task<IrStabilityDto?> GetStabilityAsync(
            string projectId, string tenantId, CancellationToken ct = default) =>
            Task.FromResult<IrStabilityDto?>(null);

        public Task<IrFragmentSnapshotDto?> GetSnapshotAtVersionAsync(
            string projectId, string tenantId, string fragmentId, int? version, CancellationToken ct = default) =>
            Task.FromResult<IrFragmentSnapshotDto?>(null);

        public Task EnsureProjectAsync(
            string projectId, string tenantId, string projectName, string creatorUserId, CancellationToken ct = default) =>
            Task.CompletedTask;
    }
}
