-- P8-C Batch 11 — ADD INDEX DDL (inteAssistant-AI remaining)
-- Generated: 2026-08-30
-- Scope: 6 tables, 12 indexes

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

PRINT '=== Batch 11 ADD INDEX START ===';

-- BASE_AI_AGENT_SKILL
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AGENTSKILL_AGENT' AND object_id = OBJECT_ID('BASE_AI_AGENT_SKILL'))
    CREATE NONCLUSTERED INDEX IDX_AGENTSKILL_AGENT ON BASE_AI_AGENT_SKILL (F_AgentId)
    INCLUDE (F_Id, F_SkillCode, F_Name, F_Enabled);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AGENTSKILL_CODE' AND object_id = OBJECT_ID('BASE_AI_AGENT_SKILL'))
    CREATE NONCLUSTERED INDEX IDX_AGENTSKILL_CODE ON BASE_AI_AGENT_SKILL (F_SkillCode)
    INCLUDE (F_Id, F_AgentId, F_Name);
PRINT '--- BASE_AI_AGENT_SKILL done ---';

-- BASE_AI_PROMPT_TEMPLATE
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_PROMPT_TENANT' AND object_id = OBJECT_ID('BASE_AI_PROMPT_TEMPLATE'))
    CREATE NONCLUSTERED INDEX IDX_PROMPT_TENANT ON BASE_AI_PROMPT_TEMPLATE (F_TenantId, F_Category)
    INCLUDE (F_Id, F_Name, F_IsActive);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_PROMPT_NAME' AND object_id = OBJECT_ID('BASE_AI_PROMPT_TEMPLATE'))
    CREATE NONCLUSTERED INDEX IDX_PROMPT_NAME ON BASE_AI_PROMPT_TEMPLATE (F_TenantId, F_Name)
    INCLUDE (F_Id, F_Category, F_Version);
PRINT '--- BASE_AI_PROMPT_TEMPLATE done ---';

-- BASE_AI_MODEL_PROVIDER
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_MODELPROVIDER_CODE' AND object_id = OBJECT_ID('BASE_AI_MODEL_PROVIDER'))
    CREATE NONCLUSTERED INDEX IDX_MODELPROVIDER_CODE ON BASE_AI_MODEL_PROVIDER (F_ProviderCode)
    INCLUDE (F_Id, F_Name, F_BaseUrl, F_Enabled);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_MODELPROVIDER_STATUS' AND object_id = OBJECT_ID('BASE_AI_MODEL_PROVIDER'))
    CREATE NONCLUSTERED INDEX IDX_MODELPROVIDER_STATUS ON BASE_AI_MODEL_PROVIDER (F_Status, F_Priority)
    INCLUDE (F_Id, F_ProviderCode, F_Name);
PRINT '--- BASE_AI_MODEL_PROVIDER done ---';

-- BASE_AI_MODEL_ROUTING
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_MODELROUTING_STAGE' AND object_id = OBJECT_ID('BASE_AI_MODEL_ROUTING'))
    CREATE NONCLUSTERED INDEX IDX_MODELROUTING_STAGE ON BASE_AI_MODEL_ROUTING (F_Stage, F_Priority)
    INCLUDE (F_Id, F_StageName, F_Provider, F_Model);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_MODELROUTING_PROVIDER' AND object_id = OBJECT_ID('BASE_AI_MODEL_ROUTING'))
    CREATE NONCLUSTERED INDEX IDX_MODELROUTING_PROVIDER ON BASE_AI_MODEL_ROUTING (F_Provider, F_Model)
    INCLUDE (F_Id, F_Stage, F_Priority);
PRINT '--- BASE_AI_MODEL_ROUTING done ---';

-- BASE_AI_CALL_LOG
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_CALLLOG_TENANT' AND object_id = OBJECT_ID('BASE_AI_CALL_LOG'))
    CREATE NONCLUSTERED INDEX IDX_CALLLOG_TENANT ON BASE_AI_CALL_LOG (F_TENANT_ID, F_CREATOR_TIME DESC)
    INCLUDE (F_ID, F_PROVIDER, F_MODEL, F_STATUS_CODE);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_CALLLOG_PROVIDER' AND object_id = OBJECT_ID('BASE_AI_CALL_LOG'))
    CREATE NONCLUSTERED INDEX IDX_CALLLOG_PROVIDER ON BASE_AI_CALL_LOG (F_PROVIDER, F_CREATOR_TIME DESC)
    INCLUDE (F_ID, F_MODEL, F_LATENCY_MS, F_STATUS_CODE);
PRINT '--- BASE_AI_CALL_LOG done ---';

-- BASE_AI_MCP_CONFIG
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_MCPCONFIG_CODE' AND object_id = OBJECT_ID('BASE_AI_MCP_CONFIG'))
    CREATE NONCLUSTERED INDEX IDX_MCPCONFIG_CODE ON BASE_AI_MCP_CONFIG (F_TENANT_ID, F_CODE)
    INCLUDE (F_ID, F_NAME, F_ENABLED);
PRINT '--- BASE_AI_MCP_CONFIG done ---';

PRINT '=== Batch 11 ADD INDEX COMPLETE ===';
COMMIT TRANSACTION;
GO
