<Project Sdk="Microsoft.NET.Sdk">
	
  <ItemGroup>
    <ProjectReference Include="..\..\common\JNPF.Common.Core\JNPF.Common.Core.csproj" />
    <ProjectReference Include="..\..\system\JNPF.Systems.Interfaces\JNPF.Systems.Interfaces.csproj" />
    <ProjectReference Include="..\..\workflow\JNPF.WorkFlow.Interfaces\JNPF.WorkFlow.Interfaces.csproj" />
    <ProjectReference Include="..\JNPF.Extend.Interfaces\JNPF.Extend.Interfaces.csproj" />
  </ItemGroup>

</Project>
