-- P8-B Batch 01 — Rollback DDL (DROP INDEX)
-- Generated: 2026-08-30
-- Mode: DROP INDEX (only if needed)
-- Status: PREPARED (NOT executed)

BEGIN TRANSACTION;

PRINT '=== Batch 01 ROLLBACK START ===';

DROP INDEX IF EXISTS IDX_ORGANIZE_PARENT ON BASE_ORGANIZE;
PRINT 'Dropped: IDX_ORGANIZE_PARENT';

DROP INDEX IF EXISTS IDX_ORGANIZE_ENCODE ON BASE_ORGANIZE;
PRINT 'Dropped: IDX_ORGANIZE_ENCODE';

DROP INDEX IF EXISTS IDX_ORGANIZE_CATEGORY ON BASE_ORGANIZE;
PRINT 'Dropped: IDX_ORGANIZE_CATEGORY';

DROP INDEX IF EXISTS IDX_ROLE_ENCODE ON BASE_ROLE;
PRINT 'Dropped: IDX_ROLE_ENCODE';

DROP INDEX IF EXISTS IDX_ROLE_TYPE ON BASE_ROLE;
PRINT 'Dropped: IDX_ROLE_TYPE';

DROP INDEX IF EXISTS IDX_POSITION_ORG ON BASE_POSITION;
PRINT 'Dropped: IDX_POSITION_ORG';

DROP INDEX IF EXISTS IDX_POSITION_ENCODE ON BASE_POSITION;
PRINT 'Dropped: IDX_POSITION_ENCODE';

DROP INDEX IF EXISTS IDX_USERRELATION_USER ON BASE_USER_RELATION;
PRINT 'Dropped: IDX_USERRELATION_USER';

DROP INDEX IF EXISTS IDX_USERRELATION_OBJECT ON BASE_USER_RELATION;
PRINT 'Dropped: IDX_USERRELATION_OBJECT';

DROP INDEX IF EXISTS IDX_USERRELATION_USER_OBJECT ON BASE_USER_RELATION;
PRINT 'Dropped: IDX_USERRELATION_USER_OBJECT';

PRINT '=== Batch 01 ROLLBACK COMPLETE ===';

COMMIT TRANSACTION;
GO
