-- Sprint 1.5: 补建 4 张缺失表
CREATE TABLE BASE_FOUNDER_AUTH_LOG (
    F_Id BIGINT PRIMARY KEY, F_UserId BIGINT NOT NULL, F_UserName NVARCHAR(50),
    F_TenantId NVARCHAR(50) NOT NULL, F_AuthType NVARCHAR(20) NOT NULL DEFAULT 'TOTP',
    F_AuthResult NVARCHAR(20) NOT NULL, F_IpAddress NVARCHAR(50), F_UserAgent NVARCHAR(500),
    F_TotpMatched BIT NOT NULL DEFAULT 0, F_FailReason NVARCHAR(200),
    F_ConsecutiveFailures INT NOT NULL DEFAULT 0, F_BlockedUntil DATETIME,
    F_CreatorTime DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_FOUNDER_AUTH_USER ON BASE_FOUNDER_AUTH_LOG(F_UserId, F_CreatorTime);
CREATE INDEX IX_FOUNDER_AUTH_RESULT ON BASE_FOUNDER_AUTH_LOG(F_AuthResult, F_CreatorTime);
CREATE INDEX IX_FOUNDER_AUTH_TENANT ON BASE_FOUNDER_AUTH_LOG(F_TenantId, F_CreatorTime);

CREATE TABLE BASE_SANDBOX (
    F_Id BIGINT PRIMARY KEY, F_TenantId NVARCHAR(50) NOT NULL,
    F_ProjectId BIGINT, F_PipelineId BIGINT,
    F_ContainerId NVARCHAR(100), F_ContainerName NVARCHAR(100),
    F_Status NVARCHAR(20) NOT NULL DEFAULT 'creating',
    F_Url NVARCHAR(500), F_SandboxAccount NVARCHAR(100) DEFAULT 'admin',
    F_SandboxPassword NVARCHAR(100) DEFAULT '123456',
    F_CpuCount INT NOT NULL DEFAULT 1, F_MemoryMb INT NOT NULL DEFAULT 1024,
    F_TimeoutSeconds INT NOT NULL DEFAULT 300,
    F_DbStrategy NVARCHAR(20) NOT NULL DEFAULT 'shared',
    F_DatabaseName NVARCHAR(100), F_ConnectionString NVARCHAR(500),
    F_CreatorTime DATETIME NOT NULL DEFAULT GETDATE(), F_CreatorUserId BIGINT,
    F_StartTime DATETIME, F_DestroyTime DATETIME, F_ErrorMessage NVARCHAR(2000),
    F_DeleteMark BIT NOT NULL DEFAULT 0
);
CREATE INDEX IX_SANDBOX_TENANT ON BASE_SANDBOX(F_TenantId, F_DeleteMark);
CREATE INDEX IX_SANDBOX_PROJECT ON BASE_SANDBOX(F_ProjectId);
CREATE INDEX IX_SANDBOX_STATUS ON BASE_SANDBOX(F_Status) WHERE F_DeleteMark = 0;

CREATE TABLE BASE_TENANT_INDUSTRY (
    F_Id BIGINT PRIMARY KEY, F_TenantId NVARCHAR(50) NOT NULL,
    F_IndustryName NVARCHAR(200) NOT NULL, F_Description NVARCHAR(MAX),
    F_KeyScenarios NVARCHAR(MAX), F_SystemPrompt NVARCHAR(MAX),
    F_Enabled BIT NOT NULL DEFAULT 1,
    F_CreatorTime DATETIME NOT NULL DEFAULT GETDATE(), F_CreatorUserId BIGINT,
    F_ModifyTime DATETIME, F_ModifyUserId BIGINT, F_DeleteMark BIT NOT NULL DEFAULT 0,
    CONSTRAINT UQ_TENANT_INDUSTRY UNIQUE (F_TenantId)
);

CREATE TABLE BASE_TENANT_GLOSSARY (
    F_Id BIGINT PRIMARY KEY, F_TenantId NVARCHAR(50) NOT NULL,
    F_Term NVARCHAR(200) NOT NULL, F_Definition NVARCHAR(2000) NOT NULL,
    F_Synonyms NVARCHAR(500), F_Category NVARCHAR(100),
    F_Example NVARCHAR(1000), F_Enabled BIT NOT NULL DEFAULT 1,
    F_CreatorTime DATETIME NOT NULL DEFAULT GETDATE(), F_CreatorUserId BIGINT,
    F_ModifyTime DATETIME, F_ModifyUserId BIGINT, F_DeleteMark BIT NOT NULL DEFAULT 0,
    CONSTRAINT UQ_TENANT_TERM UNIQUE (F_TenantId, F_Term)
);
CREATE INDEX IX_GLOSSARY_TENANT ON BASE_TENANT_GLOSSARY(F_TenantId, F_Category);
