-- Sprint 5: UI Template, Eval, Pipeline Stage tables
CREATE TABLE BASE_AI_UI_TEMPLATE (F_Id BIGINT PRIMARY KEY, F_TenantId NVARCHAR(50) DEFAULT '0', F_Name NVARCHAR(200) NOT NULL, F_Description NVARCHAR(2000), F_Category NVARCHAR(100), F_ThumbnailUrl NVARCHAR(500), F_TemplateData NVARCHAR(MAX) NOT NULL, F_Source NVARCHAR(20) DEFAULT 'official', F_DesignerId BIGINT, F_DesignerName NVARCHAR(50), F_UseCount INT DEFAULT 0, F_Rating DECIMAL(3,2) DEFAULT 5.0, F_Enabled BIT DEFAULT 1, F_CreatorTime DATETIME DEFAULT GETDATE(), F_CreatorUserId BIGINT, F_ModifyTime DATETIME, F_ModifyUserId BIGINT, F_DeleteMark BIT DEFAULT 0);
CREATE INDEX IX_TEMPLATE_CAT ON BASE_AI_UI_TEMPLATE(F_Category, F_Source, F_DeleteMark);
CREATE TABLE BASE_AI_EVAL_GOLDEN_SET (F_Id BIGINT PRIMARY KEY, F_Name NVARCHAR(200) NOT NULL, F_Description NVARCHAR(2000), F_Domain NVARCHAR(100), F_TestCaseCount INT DEFAULT 0, F_Enabled BIT DEFAULT 1, F_CreatorTime DATETIME DEFAULT GETDATE(), F_CreatorUserId BIGINT, F_ModifyTime DATETIME, F_ModifyUserId BIGINT, F_DeleteMark BIT DEFAULT 0);
CREATE TABLE BASE_AI_EVAL_CASE (F_Id BIGINT PRIMARY KEY, F_SetId BIGINT NOT NULL, F_Name NVARCHAR(200) NOT NULL, F_Requirement NVARCHAR(MAX) NOT NULL, F_ExpectedIR NVARCHAR(MAX), F_Stage INT, F_ScoreThreshold DECIMAL(3,2) DEFAULT 0.8, F_Enabled BIT DEFAULT 1, F_CreatorTime DATETIME DEFAULT GETDATE(), F_CreatorUserId BIGINT, F_ModifyTime DATETIME, F_ModifyUserId BIGINT, F_DeleteMark BIT DEFAULT 0);
CREATE TABLE BASE_AI_EVAL_RUN (F_Id BIGINT PRIMARY KEY, F_SetId BIGINT NOT NULL, F_RunAt DATETIME NOT NULL, F_TotalCases INT NOT NULL, F_PassedCases INT NOT NULL, F_AverageScore DECIMAL(5,4), F_PassRate DECIMAL(5,4), F_DurationMs BIGINT, F_Details NVARCHAR(MAX), F_CreatorTime DATETIME DEFAULT GETDATE(), F_CreatorUserId BIGINT);
CREATE INDEX IX_EVAL_RUN_SET ON BASE_AI_EVAL_RUN(F_SetId, F_RunAt);
CREATE TABLE BASE_AI_PIPELINE_STAGE_CONFIG (F_Id BIGINT PRIMARY KEY, F_Stage INT NOT NULL, F_StageName NVARCHAR(50) NOT NULL, F_Description NVARCHAR(500), F_AgentCode NVARCHAR(100), F_PromptTemplateId BIGINT, F_TimeoutSeconds INT DEFAULT 300, F_RequireConfirm BIT DEFAULT 1, F_AllowRollback BIT DEFAULT 1, F_Enabled BIT DEFAULT 1, F_CreatorTime DATETIME DEFAULT GETDATE(), F_CreatorUserId BIGINT, F_ModifyTime DATETIME, F_ModifyUserId BIGINT, F_DeleteMark BIT DEFAULT 0, CONSTRAINT UQ_STAGE_CONFIG UNIQUE (F_Stage));
INSERT INTO BASE_AI_PIPELINE_STAGE_CONFIG (F_Id,F_Stage,F_StageName,F_Description,F_AgentCode,F_TimeoutSeconds,F_RequireConfirm,F_AllowRollback,F_CreatorTime) VALUES (100000001,1,N'需求分析',N'理解业务需求',N'requirement-analyst',300,1,1,GETDATE());
INSERT INTO BASE_AI_PIPELINE_STAGE_CONFIG (F_Id,F_Stage,F_StageName,F_Description,F_AgentCode,F_TimeoutSeconds,F_RequireConfirm,F_AllowRollback,F_CreatorTime) VALUES (100000002,2,N'架构设计',N'设计系统架构',N'architect',300,1,1,GETDATE());
INSERT INTO BASE_AI_PIPELINE_STAGE_CONFIG (F_Id,F_Stage,F_StageName,F_Description,F_AgentCode,F_TimeoutSeconds,F_RequireConfirm,F_AllowRollback,F_CreatorTime) VALUES (100000003,3,N'总体设计',N'并行调用子智能体',N'orchestrator',600,1,1,GETDATE());
INSERT INTO BASE_AI_PIPELINE_STAGE_CONFIG (F_Id,F_Stage,F_StageName,F_Description,F_AgentCode,F_TimeoutSeconds,F_RequireConfirm,F_AllowRollback,F_CreatorTime) VALUES (100000004,4,N'自动开发',N'编译IR为代码',NULL,300,1,0,GETDATE());
INSERT INTO BASE_AI_PIPELINE_STAGE_CONFIG (F_Id,F_Stage,F_StageName,F_Description,F_AgentCode,F_TimeoutSeconds,F_RequireConfirm,F_AllowRollback,F_CreatorTime) VALUES (100000005,5,N'交付验证',N'测试URL+ZIP导出',NULL,300,1,0,GETDATE());
