#!/usr/bin/env python3
"""
Generate Foundry.FSPM.Mcp.Tests/obj/project.assets.json by
*cloning* the existing Foundry.FSPM.Mcp/obj/project.assets.json
(which is already in a form that ResolvePackageAssets can parse
without triggering NuGetEnvironment.GetFolderPath) and grafting
on the test-only package entries: xunit + test.sdk + ModelContextProtocol
+ their transitive closure.

Why this works
==============
The MCP project's assets.json was generated by a successful NuGet
restore and ships with all 50+ packages it depends on. The
ResolvePackageAssets task only fails when it cannot find a folder
specified in lockFile.PackageFolders; if the lockFile is structurally
correct AND every referenced package folder exists, it succeeds.

So the right strategy is:
  1. Start from MCP's lockFile (already validated).
  2. Add xunit + test.sdk + ModelContextProtocol packages to libraries,
     targets['net8.0'], projectFileDependencyGroups.
  3. Re-point project.projectUniqueName / projectPath / outputPath /
     packageFolders at the test project.

This is still a build-environment workaround (not a real restore),
but it produces a structurally valid lockFile that
ResolvePackageAssets will accept.
"""
import json
import re
import sys
from pathlib import Path

MCP_ASSETS = Path("D:/JNPF-FSPM-Worktrees/mcp/backend/modularity/Foundry.FSPM.Mcp/obj/project.assets.json")
TEST_DIR = Path("D:/JNPF-FSPM-Worktrees/mcp/backend/tests/Foundry.FSPM.Mcp.Tests")
OUT_FILE = TEST_DIR / "obj" / "project.assets.json"
PKG_ROOT = Path("E:/NuGetPackages")

# Test-only top-level packages
TEST_PKGS = [
    ("xunit", "2.6.2"),
    ("xunit.runner.visualstudio", "2.5.4"),
    ("ModelContextProtocol", "2.2.0"),
]


def read_nuspec(pkg_id: str, version: str) -> dict:
    nuspec_dir = PKG_ROOT / pkg_id.lower() / version
    candidates = list(nuspec_dir.glob("*.nuspec"))
    if not candidates:
        return {}
    text = candidates[0].read_text(encoding="utf-8")
    deps = {}
    groups = re.findall(r"<group[^>]*>(.*?)</group>", text, re.DOTALL)
    target = None
    for g in groups:
        if 'targetFramework="net8.0"' in g:
            target = g
            break
    if target is None and groups:
        target = groups[0]
    if target is None:
        m = re.search(r"<dependencies>(.*?)</dependencies>", text, re.DOTALL)
        if m:
            target = m.group(1)
    if target is None:
        return {}
    for m in re.finditer(r'<dependency\s+id="([^"]+)"\s+version="([^"]+)"', target):
        deps[m.group(1)] = m.group(2)
    return deps


def expand(initial):
    seen = set()
    queue = list(initial)
    while queue:
        pkg_id, version = queue.pop(0)
        if (pkg_id, version) in seen:
            continue
        seen.add((pkg_id, version))
        deps = read_nuspec(pkg_id, version)
        for dep_id, dep_ver_range in deps.items():
            dep_dir = PKG_ROOT / dep_id.lower()
            if not dep_dir.exists():
                continue
            available = sorted(dep_dir.iterdir(), key=lambda p: p.name)
            if not available:
                continue
            chosen = available[-1].name
            if (dep_id, chosen) not in seen:
                queue.append((dep_id, chosen))
    return seen


def find_lib_files(pkg_id: str, version: str):
    """Return a list of (relative_path, related) for every dll/xml under lib/."""
    pkg_dir = PKG_ROOT / pkg_id.lower() / version
    lib_dir = pkg_dir / "lib"
    out = []
    if not lib_dir.exists():
        return out
    for tfm_dir in sorted(lib_dir.iterdir()):
        if not tfm_dir.is_dir():
            continue
        for f in sorted(tfm_dir.glob("*.dll")):
            rel = f"lib/{tfm_dir.name}/{f.name}"
            entry = {rel: {}}
            xml = f.with_suffix(".xml")
            if xml.exists():
                entry[rel]["related"] = ".xml"
            out.append(entry)
    return out


def build_pkg_entry(pkg_id: str, version: str) -> dict:
    deps = read_nuspec(pkg_id, version)
    entry = {"type": "package", "dependencies": deps}
    files = find_lib_files(pkg_id, version)
    if files:
        entry["compile"] = {list(c.keys())[0]: list(c.values())[0] for c in files}
        entry["runtime"] = {list(c.keys())[0]: list(c.values())[0] for c in files}
        # also include under tfm-specific keys
    return entry


def main():
    mcp = json.loads(MCP_ASSETS.read_text(encoding="utf-8"))
    # 1. Find all test-side packages (top-level + transitive)
    test_pkg_set = expand(set(TEST_PKGS))
    print(f"[gen-assets] test-side packages: {len(test_pkg_set)}")

    # 2. For each, build an entry. Only add to targets.net8.0.
    for pkg_id, version in sorted(test_pkg_set):
        key = f"{pkg_id}/{version}"
        if not (PKG_ROOT / pkg_id.lower() / version).exists():
            print(f"[gen-assets] SKIP missing on disk: {key}")
            continue
        if key in mcp["libraries"]:
            continue
        pkg_dir = PKG_ROOT / pkg_id.lower() / version
        files = []
        for f in pkg_dir.rglob("*"):
            if f.is_file():
                files.append(str(f.relative_to(pkg_dir)).replace("\\", "/"))
        mcp["libraries"][key] = {
            "sha512": "0" * 88,
            "type": "package",
            "path": f"{pkg_id.lower()}/{version}",
            "files": files,
        }
        mcp["targets"]["net8.0"][key] = build_pkg_entry(pkg_id, version)

    # 3. Update projectFileDependencyGroups + project.frameworks.net8.0.dependencies
    mcp["projectFileDependencyGroups"]["net8.0"] = [f"{p} >= {v}" for p, v in TEST_PKGS]
    mcp["project"]["frameworks"]["net8.0"]["dependencies"] = {p: v for p, v in TEST_PKGS}
    mcp["project"]["restore"]["projectUniqueName"] = str(TEST_DIR / "Foundry.FSPM.Mcp.Tests.csproj")
    mcp["project"]["restore"]["projectName"] = "Foundry.FSPM.Mcp.Tests"
    mcp["project"]["restore"]["projectPath"] = str(TEST_DIR / "Foundry.FSPM.Mcp.Tests.csproj")
    mcp["project"]["restore"]["outputPath"] = str(TEST_DIR / "obj")
    mcp["project"]["restore"]["originalTargetFrameworks"] = ["net8.0"]
    mcp["project"]["restore"]["frameworks"]["net8.0"]["dependencies"] = {p: v for p, v in TEST_PKGS}
    # packageFolders must be exactly the ones we have on disk.
    mcp["project"]["restore"]["packagesPath"] = "E:\\NuGetPackages"
    mcp["project"]["restore"]["fallbackFolders"] = [
        "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\NuGetPackages"
    ]
    mcp["project"]["version"] = "1.0.0"

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(json.dumps(mcp, indent=2), encoding="utf-8")
    print(f"[gen-assets] wrote {OUT_FILE} ({OUT_FILE.stat().st_size} bytes)")
    print(f"[gen-assets] total libraries: {len(mcp['libraries'])}")


if __name__ == "__main__":
    main()
