<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="D:/JNPF-v52/backend/framework/JNPF/JNPF.csproj" />
    <ProjectReference Include="D:/JNPF-v52/backend/framework/JNPF.Extras.DatabaseAccessor.SqlSugar/JNPF.Extras.DatabaseAccessor.SqlSugar.csproj" />
    <ProjectReference Include="D:/JNPF-v52/backend/modularity/common/JNPF.Common/JNPF.Common.csproj" />
    <ProjectReference Include="D:/JNPF-v52/backend/modularity/common/JNPF.Common.Core/JNPF.Common.Core.csproj" />
    <ProjectReference Include="D:/JNPF-v52/backend/modularity/system/JNPF.Systems.Interfaces/JNPF.Systems.Interfaces.csproj" />
    <ProjectReference Include="D:/JNPF-v52/backend/modularity/system/JNPF.Systems/JNPF.Systems.csproj" />
    <ProjectReference Include="D:/JNPF-v52/backend/modularity/workflow/JNPF.WorkFlow.Entitys/JNPF.WorkFlow.Entitys.csproj" />
    <ProjectReference Include="D:/JNPF-v52/backend/modularity/engine/JNPF.Engine.Entity/JNPF.Engine.Entity.csproj" />
    <ProjectReference Include="D:/JNPF-v52/backend/modularity/engine/JNPF.VisualDev.Engine/JNPF.VisualDev.Engine.csproj" />
    <ProjectReference Include="D:/JNPF-v52/backend/modularity/visualdev/JNPF.VisualDev.Interfaces/JNPF.VisualDev.Interfaces.csproj" />
  </ItemGroup>
</Project>
