// <auto-generated> Q2 violation probe — AG-002 missing tenant guard patterns
namespace JNPF.OaLeave.Services;

public sealed class NoTenantProbeService
{
    public object GetList() => new object();
}
