SET SHOWPLAN_TEXT ON;
GO
SELECT F_ID, F_SOURCE_NODE_ID FROM BASE_KNOWLEDGE_EDGE WHERE F_TENANT_ID = 'default' AND F_SOURCE_NODE_ID = 'TEST_VALUE';
GO
SET SHOWPLAN_TEXT OFF;
GO
SELECT F_ID, F_TARGET_NODE_ID FROM BASE_KNOWLEDGE_EDGE WHERE F_TENANT_ID = 'default' AND F_TARGET_NODE_ID = 'TEST_VALUE';
GO
SET SHOWPLAN_TEXT ON;
SELECT F_ID, F_TARGET_NODE_ID FROM BASE_KNOWLEDGE_EDGE WHERE F_TENANT_ID = 'default' AND F_TARGET_NODE_ID = 'TEST_VALUE';
GO
SET SHOWPLAN_TEXT OFF;
GO
SELECT F_ID, F_RELATION_TYPE FROM BASE_KNOWLEDGE_EDGE WHERE F_TENANT_ID = 'default' AND F_RELATION_TYPE = 'contains';
GO
SET SHOWPLAN_TEXT ON;
SELECT F_ID, F_RELATION_TYPE FROM BASE_KNOWLEDGE_EDGE WHERE F_TENANT_ID = 'default' AND F_RELATION_TYPE = 'contains';
GO
SET SHOWPLAN_TEXT OFF;
