-- P8-C Batch 17 — ADD INDEX DDL (BASE_AI_* remaining)
-- Generated: 2026-08-30
-- Scope: 11 tables, ~17 indexes
-- Note: many BASE_AI_* tables have NO tenant_id column

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

PRINT '=== Batch 17 ADD INDEX START ===';

-- BASE_AI_AGENT_CONFIG (no tenant, only F_AgentCode)
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIAGENTCFG_TYPE' AND object_id = OBJECT_ID('BASE_AI_AGENT_CONFIG'))
    CREATE NONCLUSTERED INDEX IDX_AIAGENTCFG_TYPE ON BASE_AI_AGENT_CONFIG (F_AgentType)
    INCLUDE (F_Id, F_Name, F_AgentCode, F_Enabled);
PRINT '--- BASE_AI_AGENT_CONFIG done ---';

-- BASE_AI_AGENT_SKILL (no tenant)
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIAGENTSKILL_TYPE' AND object_id = OBJECT_ID('BASE_AI_AGENT_SKILL'))
    CREATE NONCLUSTERED INDEX IDX_AIAGENTSKILL_TYPE ON BASE_AI_AGENT_SKILL (F_SkillType, F_Enabled)
    INCLUDE (F_Id, F_AgentId, F_Name);
PRINT '--- BASE_AI_AGENT_SKILL done ---';

-- BASE_AI_EVAL_CASE
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIEVALCASE_SET' AND object_id = OBJECT_ID('BASE_AI_EVAL_CASE'))
    CREATE NONCLUSTERED INDEX IDX_AIEVALCASE_SET ON BASE_AI_EVAL_CASE (F_SetId, F_CaseCode)
    INCLUDE (F_Id, F_CaseName, F_ExpectedVerdict);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIEVALCASE_VERDICT' AND object_id = OBJECT_ID('BASE_AI_EVAL_CASE'))
    CREATE NONCLUSTERED INDEX IDX_AIEVALCASE_VERDICT ON BASE_AI_EVAL_CASE (F_ExpectedVerdict)
    INCLUDE (F_Id, F_SetId, F_CaseCode);
PRINT '--- BASE_AI_EVAL_CASE done ---';

-- BASE_AI_EVAL_GOLDEN_SET
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIEVALGSET_NAME' AND object_id = OBJECT_ID('BASE_AI_EVAL_GOLDEN_SET'))
    CREATE NONCLUSTERED INDEX IDX_AIEVALGSET_NAME ON BASE_AI_EVAL_GOLDEN_SET (F_Name)
    INCLUDE (F_Id, F_Version, F_Description);
PRINT '--- BASE_AI_EVAL_GOLDEN_SET done ---';

-- BASE_AI_GENERATED_PROJECT (25 cols)
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIGENPROJ_PROJECT' AND object_id = OBJECT_ID('BASE_AI_GENERATED_PROJECT'))
    CREATE NONCLUSTERED INDEX IDX_AIGENPROJ_PROJECT ON BASE_AI_GENERATED_PROJECT (F_TenantId, F_ProjectId)
    INCLUDE (F_Id, F_Name, F_Status, F_CreatorTime);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIGENPROJ_STATUS' AND object_id = OBJECT_ID('BASE_AI_GENERATED_PROJECT'))
    CREATE NONCLUSTERED INDEX IDX_AIGENPROJ_STATUS ON BASE_AI_GENERATED_PROJECT (F_Status, F_CreatorTime DESC)
    INCLUDE (F_Id, F_Name, F_TenantId);
PRINT '--- BASE_AI_GENERATED_PROJECT done ---';

-- BASE_AI_MODEL_PROVIDER
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIMODELPROV_NAME' AND object_id = OBJECT_ID('BASE_AI_MODEL_PROVIDER'))
    CREATE NONCLUSTERED INDEX IDX_AIMODELPROV_NAME ON BASE_AI_MODEL_PROVIDER (F_Name)
    INCLUDE (F_Id, F_ProviderCode, F_BaseUrl);
PRINT '--- BASE_AI_MODEL_PROVIDER done ---';

-- BASE_AI_MODEL_ROUTING
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIMODELROUTE_ENABLED' AND object_id = OBJECT_ID('BASE_AI_MODEL_ROUTING'))
    CREATE NONCLUSTERED INDEX IDX_AIMODELROUTE_ENABLED ON BASE_AI_MODEL_ROUTING (F_Enabled, F_Priority)
    INCLUDE (F_Id, F_Stage, F_Provider);
PRINT '--- BASE_AI_MODEL_ROUTING done ---';

-- BASE_AI_PIPELINE_S2_PROGRESS
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIPIPES2_PROJECT' AND object_id = OBJECT_ID('BASE_AI_PIPELINE_S2_PROGRESS'))
    CREATE NONCLUSTERED INDEX IDX_AIPIPES2_PROJECT ON BASE_AI_PIPELINE_S2_PROGRESS (F_TenantId, F_ProjectId, F_PIPELINE_ID)
    INCLUDE (F_Id, F_Stage, F_Status, F_UpdateTime);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIPIPES2_STAGE' AND object_id = OBJECT_ID('BASE_AI_PIPELINE_S2_PROGRESS'))
    CREATE NONCLUSTERED INDEX IDX_AIPIPES2_STAGE ON BASE_AI_PIPELINE_S2_PROGRESS (F_Stage, F_Status)
    INCLUDE (F_Id, F_PIPELINE_ID);
PRINT '--- BASE_AI_PIPELINE_S2_PROGRESS done ---';

-- BASE_AI_PIPELINE_STAGE_CONFIG
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIPIPESTG_PIPELINE' AND object_id = OBJECT_ID('BASE_AI_PIPELINE_STAGE_CONFIG'))
    CREATE NONCLUSTERED INDEX IDX_AIPIPESTG_PIPELINE ON BASE_AI_PIPELINE_STAGE_CONFIG (F_PIPELINE_ID, F_StageOrder)
    INCLUDE (F_Id, F_StageName, F_StageType);
PRINT '--- BASE_AI_PIPELINE_STAGE_CONFIG done ---';

-- BASE_AI_PROMPT_TEMPLATE
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIPROMPT_NAME' AND object_id = OBJECT_ID('BASE_AI_PROMPT_TEMPLATE'))
    CREATE NONCLUSTERED INDEX IDX_AIPROMPT_NAME ON BASE_AI_PROMPT_TEMPLATE (F_TenantId, F_Name)
    INCLUDE (F_Id, F_Category, F_IsActive);
PRINT '--- BASE_AI_PROMPT_TEMPLATE done ---';

-- BASE_AI_UI_TEMPLATE
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIUITEMPL_TYPE' AND object_id = OBJECT_ID('BASE_AI_UI_TEMPLATE'))
    CREATE NONCLUSTERED INDEX IDX_AIUITEMPL_TYPE ON BASE_AI_UI_TEMPLATE (F_TemplateType)
    INCLUDE (F_Id, F_Name, F_Version);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AIUITEMPL_NAME' AND object_id = OBJECT_ID('BASE_AI_UI_TEMPLATE'))
    CREATE NONCLUSTERED INDEX IDX_AIUITEMPL_NAME ON BASE_AI_UI_TEMPLATE (F_Name)
    INCLUDE (F_Id, F_TemplateType, F_Version);
PRINT '--- BASE_AI_UI_TEMPLATE done ---';

PRINT '=== Batch 17 ADD INDEX COMPLETE ===';
COMMIT TRANSACTION;
GO
