-- PostgreSQL DDL 脚本（由 SQL Server 脚本自动转换）
-- 源文件: 主库脚本.sql (SQL Server SSMS 导出)
-- 转换目标: PostgreSQL 15+
-- 生成工具: sqlserver_to_pg.py

CREATE TABLE JOBCLUSTER(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	CLUSTERID varchar(64) NOT NULL,
	DESCRIPTION varchar(128) NULL,
	STATUS smallint NOT NULL,
	UPDATEDTIME timestamp NULL,
 CONSTRAINT PK_JOBCLUSTER_ID PRIMARY KEY 
(
	ID 
) 
) 
CREATE TABLE JOBDETAILS(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	JOBID varchar(64) NOT NULL,
	GROUPNAME varchar(128) NULL,
	JOBTYPE varchar(128) NULL,
	ASSEMBLYNAME varchar(128) NULL,
	DESCRIPTION varchar(128) NULL,
	CONCURRENT smallint NOT NULL,
	INCLUDEANNOTATIONS smallint NOT NULL,
	PROPERTIES text NULL,
	UPDATEDTIME timestamp NULL,
	CREATETYPE integer NOT NULL,
	SCRIPTCODE text NULL,
	TENANTID varchar(50) NULL,
 CONSTRAINT PK_JOBDETAILS_ID PRIMARY KEY 
(
	ID 
) 
)  
CREATE TABLE JOBTRIGGERS(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	TRIGGERID varchar(64) NOT NULL,
	JOBID varchar(64) NOT NULL,
	TRIGGERTYPE varchar(128) NULL,
	ASSEMBLYNAME varchar(128) NULL,
	ARGS varchar(128) NULL,
	DESCRIPTION varchar(128) NULL,
	STATUS smallint NOT NULL,
	STARTTIME timestamp NULL,
	ENDTIME timestamp NULL,
	LASTRUNTIME timestamp NULL,
	NEXTRUNTIME timestamp NULL,
	NUMBEROFRUNS integer NOT NULL,
	MAXNUMBEROFRUNS integer NOT NULL,
	NUMBEROFERRORS integer NOT NULL,
	MAXNUMBEROFERRORS integer NOT NULL,
	NUMRETRIES integer NOT NULL,
	RETRYTIMEOUT integer NOT NULL,
	STARTNOW smallint NOT NULL,
	RUNONSTART smallint NOT NULL,
	RESETONLYONCE smallint NOT NULL,
	UPDATEDTIME timestamp NULL,
 CONSTRAINT PK_JOBTRIGGERS_ID PRIMARY KEY 
(
	ID 
) 
) 
USE master
ALTER DATABASE jnpf_sundial SET  READ_WRITE 