SET NOCOUNT ON;
SET STATISTICS TIME ON;
SELECT TOP 20 a.F_ID, a.F_ORDER_CODE, a.F_CUSTOMER_NAME, b.F_REAL_NAME, b.F_ACCOUNT, c.F_STATUS
FROM ext_order a
LEFT JOIN base_user b ON a.F_CREATOR_USER_ID = b.F_ID
LEFT JOIN flow_task c ON a.F_ID = c.F_ID
WHERE a.F_DELETE_MARK IS NULL
ORDER BY a.F_CREATOR_TIME DESC;
SET STATISTICS TIME OFF;

-- 子查询成本：明细+收款（GetInfo 等价）
SET STATISTICS TIME ON;
SELECT * FROM ext_order_entry WHERE F_ORDER_ID IS NOT NULL;
SELECT * FROM ext_order_receivable WHERE F_ORDER_ID IS NOT NULL;
SET STATISTICS TIME OFF;

-- 权限三连查（authorize -> module -> scheme 等价）
SET STATISTICS TIME ON;
SELECT TOP 5 * FROM base_module WHERE F_EN_CODE = 'extend.order';
SET STATISTICS TIME OFF;
