<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\common\JNPF.Common.Core\JNPF.Common.Core.csproj" />
    <ProjectReference Include="..\..\message\JNPF.Message.Interfaces\JNPF.Message.Interfaces.csproj" />
    <ProjectReference Include="..\..\system\JNPF.Systems.Interfaces\JNPF.Systems.Interfaces.csproj" />
    <ProjectReference Include="..\JNPF.InteAssistant.Engine\JNPF.InteAssistant.Engine.csproj" />
    <ProjectReference Include="..\JNPF.InteAssistant.Entitys\JNPF.InteAssistant.Entitys.csproj" />
  </ItemGroup>

</Project>
