<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\common\JNPF.Common.Core\JNPF.Common.Core.csproj" />
    <ProjectReference Include="..\..\message\JNPF.Message.Interfaces\JNPF.Message.Interfaces.csproj" />
    <ProjectReference Include="..\..\system\JNPF.Systems.Interfaces\JNPF.Systems.Interfaces.csproj" />
    <ProjectReference Include="..\JNPF.InteAssistant.Engine\JNPF.InteAssistant.Engine.csproj" />
    <ProjectReference Include="..\JNPF.InteAssistant.Entitys\JNPF.InteAssistant.Entitys.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.14" />
    <PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1" />
  </ItemGroup>

</Project>
