<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\common\JNPF.Common.Core\JNPF.Common.Core.csproj" />
    <ProjectReference Include="..\..\message\JNPF.Message.Interfaces\JNPF.Message.Interfaces.csproj" />
    <ProjectReference Include="..\..\system\JNPF.Systems.Interfaces\JNPF.Systems.Interfaces.csproj" />
    <ProjectReference Include="..\JNPF.InteAssistant.Engine\JNPF.InteAssistant.Engine.csproj" />
    <ProjectReference Include="..\JNPF.InteAssistant.Entitys\JNPF.InteAssistant.Entitys.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="5.8.4" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.14" />
    <PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.1" />
    <PackageReference Include="NPOI" Version="2.8.0" />
    <PackageReference Include="PdfPig" Version="0.1.9" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1" />
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>

</Project>
