-- P8-B Batch 02 — Rollback DDL (DROP INDEX)
-- Generated: 2026-08-30
-- Status: PREPARED (NOT executed)

BEGIN TRANSACTION;

PRINT '=== Batch 02 ROLLBACK START ===';

DROP INDEX IF EXISTS IDX_AUTHORIZE_OBJECT ON base_authorize;
DROP INDEX IF EXISTS IDX_AUTHORIZE_ITEM ON base_authorize;
DROP INDEX IF EXISTS IDX_AUTHORIZE_OBJECT_ITEM ON base_authorize;

DROP INDEX IF EXISTS IDX_MODULE_PARENT ON base_module;
DROP INDEX IF EXISTS IDX_MODULE_TYPE ON base_module;
DROP INDEX IF EXISTS IDX_MODULE_CATEGORY ON base_module;

DROP INDEX IF EXISTS IDX_BUTTON_MODULE ON base_module_button;
DROP INDEX IF EXISTS IDX_BUTTON_PARENT ON base_module_button;

DROP INDEX IF EXISTS IDX_COLUMN_MODULE ON base_module_column;
DROP INDEX IF EXISTS IDX_COLUMN_BINDTABLE ON base_module_column;

DROP INDEX IF EXISTS IDX_FORM_MODULE ON base_module_form;
DROP INDEX IF EXISTS IDX_FORM_BINDTABLE ON base_module_form;

PRINT '=== Batch 02 ROLLBACK COMPLETE ===';

COMMIT TRANSACTION;
GO
