/**
 * 编译产物 → ZIP 打包引擎
 *
 * 将 GeneratedProject (Map<string, string>) 打包为可下载的 zip。
 * 纯前端实现，基于 JSZip。
 *
 * @jnpf-generated v5.2.0 type=zip-bundler platform=universal
 */

import JSZip from 'jszip';
import type { GeneratedProject } from '../vue3/types';

export interface BundleOptions {
  /** ZIP 文件名（不含 .zip 后缀） */
  fileName: string;
  /** 是否包含 README */
  includeReadme?: boolean;
  /** README 内容 */
  readmeContent?: string;
  /** 是否包含 .gitignore */
  includeGitignore?: boolean;
}

/**
 * 将 GeneratedProject 打包为 ZIP Blob
 */
export async function bundleToZip(project: GeneratedProject, options: BundleOptions): Promise<Blob> {
  const zip = new JSZip();

  // 写入所有生成文件
  for (const [path, content] of project) {
    zip.file(path, content);
  }

  // README
  if (options.includeReadme !== false) {
    zip.file('README.md', options.readmeContent ?? generateDefaultReadme(options.fileName));
  }

  // .gitignore
  if (options.includeGitignore !== false) {
    zip.file('.gitignore', generateGitignore());
  }

  return zip.generateAsync({ type: 'blob' });
}

/**
 * 触发浏览器下载
 */
export function downloadZip(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${fileName}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * 一键编译 + 下载
 */
export async function compileAndDownload(project: GeneratedProject, entity: string, target: string): Promise<void> {
  const fileName = `jnpf-${entity}-${target}`;
  const blob = await bundleToZip(project, {
    fileName,
    includeReadme: true,
    readmeContent: generateProjectReadme(entity, target),
  });
  downloadZip(blob, fileName);
}

// ─── 模板 ───

function generateDefaultReadme(name: string): string {
  return `# ${name}

Generated by JNPF v5.2 Low-Code Platform.

## Quick Start

\`\`\`bash
npm install
npm run dev
\`\`\`
`;
}

function generateProjectReadme(entity: string, target: string): string {
  return `# ${entity} — ${target}

Generated by JNPF v5.2 Low-Code Platform.
Target: ${target}
Entity: ${entity}
Date: ${new Date().toISOString()}

## Quick Start

\`\`\`bash
npm install
npm run dev
\`\`\`

## Notes

- Generated code — manual edits may be overwritten.
- Use @jnpf-gen:insert-point for custom extensions.
`;
}

function generateGitignore(): string {
  return `node_modules/
dist/
.DS_Store
*.local
.env.local
.env.*.local
npm-debug.log*
`;
}
