-- 流水线任务意图（全量 / Debug / 二次开发）
SET QUOTED_IDENTIFIER ON;
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'BASE_AI_PIPELINE') AND name = N'F_WORK_MODE')
    ALTER TABLE [dbo].[BASE_AI_PIPELINE] ADD [F_WORK_MODE] NVARCHAR(32) NOT NULL CONSTRAINT [DF_pipeline_work_mode] DEFAULT 'greenfield';
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'BASE_AI_PIPELINE') AND name = N'F_SOURCE_PIPELINE_ID')
    ALTER TABLE [dbo].[BASE_AI_PIPELINE] ADD [F_SOURCE_PIPELINE_ID] NVARCHAR(50) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'BASE_AI_PIPELINE') AND name = N'F_TARGET_PAGE_ROUTE')
    ALTER TABLE [dbo].[BASE_AI_PIPELINE] ADD [F_TARGET_PAGE_ROUTE] NVARCHAR(500) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'BASE_AI_PIPELINE') AND name = N'F_TARGET_PAGE_LABEL')
    ALTER TABLE [dbo].[BASE_AI_PIPELINE] ADD [F_TARGET_PAGE_LABEL] NVARCHAR(200) NULL;
GO
