-- ========================================
-- 第六章数据库设计补丁（玛维思汇总清单执行）
-- 日期：2026-06-20
-- ========================================

-- ==================== DB-09: BASE_AI_PIPELINE_MESSAGE 补充字段 ====================
ALTER TABLE BASE_AI_PIPELINE_MESSAGE ADD F_NOTIFY_TARGETS NVARCHAR(500) NULL;

-- ==================== DB-16: BASE_USER 密码字段扩展 ====================
ALTER TABLE BASE_USER ALTER COLUMN F_PASSWORD NVARCHAR(255) NOT NULL;

-- ==================== DB-17: 知识图谱乐观锁 ====================
ALTER TABLE BASE_KNOWLEDGE_NODE ADD F_VERSION INT NOT NULL DEFAULT 0;
ALTER TABLE BASE_KNOWLEDGE_EDGE ADD F_VERSION INT NOT NULL DEFAULT 0;

-- ==================== DB-21: 6 个关键索引 ====================
CREATE INDEX IDX_PIPELINE_MSG_QUERY ON BASE_AI_PIPELINE_MESSAGE(F_PIPELINE_ID, F_STAGE, F_CREATOR_TIME DESC);
CREATE INDEX IDX_AI_CALL_LOG_QUERY ON BASE_AI_CALL_LOG(F_TENANT_ID, F_CREATOR_TIME DESC, F_PROVIDER);
CREATE INDEX IDX_IR_VERSION_QUERY ON BASE_IR_VERSION(F_PIPELINE_ID, F_SNAPSHOT_AT DESC);
CREATE INDEX IDX_EDIT_PATCH_STATUS ON BASE_IR_EDIT_PATCH(F_PIPELINE_ID, F_STATUS, F_CREATOR_TIME DESC);
CREATE INDEX IDX_SANDBOX_TENANT ON BASE_SANDBOX(F_TENANT_ID, F_STATUS);
CREATE INDEX IDX_KNOWLEDGE_NODE_TYPE ON BASE_KNOWLEDGE_NODE(F_NODE_TYPE, F_TENANT_ID);

-- ==================== DB-28: EVAL_METRIC 评分指标定义表 ====================
CREATE TABLE EVAL_METRIC (
    F_ID              BIGINT NOT NULL PRIMARY KEY,
    F_METRIC_CODE     NVARCHAR(50) NOT NULL,
    F_METRIC_NAME     NVARCHAR(100) NOT NULL,
    F_METRIC_TYPE     NVARCHAR(20) NOT NULL,
    F_THRESHOLD_WARN  DECIMAL(10,4) NULL,
    F_THRESHOLD_CRIT  DECIMAL(10,4) NULL,
    F_UNIT            NVARCHAR(20) NULL,
    F_DESCRIPTION     NVARCHAR(500) NULL,
    F_TENANT_ID       NVARCHAR(50) NOT NULL DEFAULT 'default',
    F_CREATOR_USER_ID NVARCHAR(50) NULL,
    F_CREATOR_TIME    DATETIME NULL,
    F_LAST_MODIFY_USER_ID NVARCHAR(50) NULL,
    F_LAST_MODIFY_TIME    DATETIME NULL
);

-- ==================== DB-20: 知识图谱备份表清理索引 ====================
CREATE INDEX IDX_KNOWLEDGE_BACKUP_CLEANUP ON BASE_KNOWLEDGE_NODE_BACKUP(F_BACKUP_TIME);

-- ==================== 验证SQL ====================
-- SELECT F_NOTIFY_TARGETS FROM BASE_AI_PIPELINE_MESSAGE WHERE 1=0;
-- SELECT F_VERSION FROM BASE_KNOWLEDGE_NODE WHERE 1=0;
-- SELECT F_VERSION FROM BASE_KNOWLEDGE_EDGE WHERE 1=0;
-- SELECT * FROM EVAL_METRIC WHERE 1=0;
-- SELECT name FROM sys.indexes WHERE name LIKE 'IDX_%';
