-- ========================================
-- 议题5 B-11: AI调用日志降级追踪字段
-- 日期：2026-06-20
-- ========================================

ALTER TABLE BASE_AI_CALL_LOG ADD F_FALLBACK INT DEFAULT 0;
ALTER TABLE BASE_AI_CALL_LOG ADD F_ORIGINAL_MODEL NVARCHAR(50) NULL;
ALTER TABLE BASE_AI_CALL_LOG ADD F_ACTUAL_MODEL NVARCHAR(50) NULL;
ALTER TABLE BASE_AI_CALL_LOG ADD F_FALLBACK_REASON NVARCHAR(200) NULL;

-- 验证 SQL:
-- SELECT F_FALLBACK, F_ORIGINAL_MODEL, F_ACTUAL_MODEL, F_FALLBACK_REASON FROM BASE_AI_CALL_LOG WHERE 1=0;
