-- ========================================
-- JNPF AI流水线 完整数据库初始化
-- 包含：建表 + 全部四份裁决书字段变更
-- 日期：2026-06-20
-- ========================================

-- ==================== 1. BASE_AI_CALL_LOG ====================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='BASE_AI_CALL_LOG' AND xtype='U')
CREATE TABLE BASE_AI_CALL_LOG (
    F_ID               NVARCHAR(50) PRIMARY KEY,
    F_PROVIDER         NVARCHAR(50) NULL,
    F_MODEL            NVARCHAR(100) NULL,
    F_PROMPT_TOKENS    INT NULL,
    F_COMPLETION_TOKENS INT NULL,
    F_LATENCY_MS       BIGINT NULL,
    F_STATUS_CODE      INT NULL,
    F_REQUEST_BODY     NVARCHAR(MAX) NULL,
    F_RESPONSE_BODY    NVARCHAR(MAX) NULL,
    F_FALLBACK         INT DEFAULT 0,
    F_ORIGINAL_MODEL   NVARCHAR(50) NULL,
    F_ACTUAL_MODEL     NVARCHAR(50) NULL,
    F_FALLBACK_REASON  NVARCHAR(200) NULL,
    F_TENANT_ID        NVARCHAR(50) NOT NULL DEFAULT 'default',
    F_CREATOR_TIME     DATETIME NULL,
    F_CREATOR_USER_ID  NVARCHAR(50) NULL,
    F_LAST_MODIFY_TIME DATETIME NULL,
    F_LAST_MODIFY_USER_ID NVARCHAR(50) NULL,
    F_DELETE_MARK      INT DEFAULT 0,
    F_SORT_CODE        BIGINT NULL,
    F_ENABLED_MARK     INT DEFAULT 1
);

-- ==================== 2. BASE_AI_PIPELINE ====================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='BASE_AI_PIPELINE' AND xtype='U')
CREATE TABLE BASE_AI_PIPELINE (
    F_ID               NVARCHAR(50) PRIMARY KEY,
    F_NAME             NVARCHAR(200) NULL,
    F_CURRENT_STAGE    NVARCHAR(50) NULL,
    F_STATUS           NVARCHAR(50) NULL,
    F_STAGE_STATUS     INT NULL,
    F_STARTED_TIME     DATETIME NULL,
    F_FINISHED_TIME    DATETIME NULL,
    F_VALIDATION_ID    NVARCHAR(50) NULL,
    F_STALE_FROM_STAGE NVARCHAR(50) NULL,
    F_REJECT_COUNT     INT NOT NULL DEFAULT 0,
    F_ABANDONED_AT     DATETIME NULL,
    F_ABANDONED_BY     NVARCHAR(50) NULL,
    F_ABANDON_REASON   NVARCHAR(500) NULL,
    F_STALE_SINCE      DATETIME NULL,
    F_STALE_AT         DATETIME NULL,
    F_FAILURE_COUNTS   NVARCHAR(MAX) NULL,
    F_TENANT_ID        NVARCHAR(50) NOT NULL DEFAULT 'default',
    F_CREATOR_TIME     DATETIME NULL,
    F_CREATOR_USER_ID  NVARCHAR(50) NULL,
    F_LAST_MODIFY_TIME DATETIME NULL,
    F_LAST_MODIFY_USER_ID NVARCHAR(50) NULL,
    F_DELETE_MARK      INT DEFAULT 0,
    F_SORT_CODE        BIGINT NULL,
    F_ENABLED_MARK     INT DEFAULT 1
);

-- ==================== 3. BASE_AI_PIPELINE_MESSAGE ====================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='BASE_AI_PIPELINE_MESSAGE' AND xtype='U')
CREATE TABLE BASE_AI_PIPELINE_MESSAGE (
    F_ID               NVARCHAR(50) PRIMARY KEY,
    F_PIPELINE_ID      NVARCHAR(50) NULL,
    F_ROLE             NVARCHAR(50) NULL,
    F_CONTENT          NVARCHAR(MAX) NULL,
    F_STAGE            NVARCHAR(50) NULL,
    F_SEQUENCE         INT NULL,
    F_NOTIFY_TARGETS   NVARCHAR(500) NULL,
    F_TENANT_ID        NVARCHAR(50) NOT NULL DEFAULT 'default',
    F_CREATOR_TIME     DATETIME NULL,
    F_CREATOR_USER_ID  NVARCHAR(50) NULL,
    F_LAST_MODIFY_TIME DATETIME NULL,
    F_LAST_MODIFY_USER_ID NVARCHAR(50) NULL,
    F_DELETE_MARK      INT DEFAULT 0,
    F_SORT_CODE        BIGINT NULL,
    F_ENABLED_MARK     INT DEFAULT 1
);

-- ==================== 4. BASE_IR_VERSION ====================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='BASE_IR_VERSION' AND xtype='U')
CREATE TABLE BASE_IR_VERSION (
    F_ID                NVARCHAR(50) PRIMARY KEY,
    F_PIPELINE_ID       NVARCHAR(50) NULL,
    F_VERSION           INT NOT NULL,
    F_TRIGGERED_BY      NVARCHAR(100) NULL,
    F_CHANGE_SUMMARY    NVARCHAR(500) NULL,
    F_PARENT_VERSION_ID BIGINT NULL,
    F_DIFF              NVARCHAR(MAX) DEFAULT '[]',
    F_CHANGE_TYPE       NVARCHAR(20) NULL,
    F_EDIT_PATCH_ID     BIGINT NULL,
    F_VALIDATION_RESULT NVARCHAR(MAX) NULL,
    F_SNAPSHOT_AT       DATETIME NULL,
    F_IR_SNAPSHOT       NVARCHAR(MAX) NULL,
    F_TENANT_ID         NVARCHAR(50) NOT NULL DEFAULT 'default',
    F_CREATOR_TIME      DATETIME NULL,
    F_CREATOR_USER_ID   NVARCHAR(50) NULL,
    F_LAST_MODIFY_TIME  DATETIME NULL,
    F_LAST_MODIFY_USER_ID NVARCHAR(50) NULL,
    F_DELETE_MARK       INT DEFAULT 0,
    F_SORT_CODE         BIGINT NULL,
    F_ENABLED_MARK      INT DEFAULT 1
);

-- ==================== 5. BASE_IR_EDIT_PATCH ====================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='BASE_IR_EDIT_PATCH' AND xtype='U')
CREATE TABLE BASE_IR_EDIT_PATCH (
    F_ID               BIGINT NOT NULL PRIMARY KEY,
    F_PIPELINE_ID      BIGINT NOT NULL,
    F_VERSION_ID       BIGINT NULL,
    F_TARGET_NODE_IDS  NVARCHAR(MAX) NOT NULL,
    F_OPERATIONS       NVARCHAR(MAX) NOT NULL,
    F_EXPLANATION      NVARCHAR(500) NULL,
    F_STATUS           NVARCHAR(20) NOT NULL DEFAULT 'pending',
    F_APPLIED_COUNT    INT NOT NULL DEFAULT 0,
    F_FAILED_COUNT     INT NOT NULL DEFAULT 0,
    F_CHANGE_TYPE      NVARCHAR(20) NOT NULL DEFAULT 'surgical_edit',
    F_TENANT_ID        NVARCHAR(50) NOT NULL DEFAULT 'default',
    F_CREATOR_USER_ID  NVARCHAR(50) NULL,
    F_CREATOR_TIME     DATETIME NULL,
    F_LAST_MODIFY_USER_ID NVARCHAR(50) NULL,
    F_LAST_MODIFY_TIME    DATETIME NULL,
    F_DELETE_MARK      INT DEFAULT 0
);

-- ==================== 6. EVAL_METRIC ====================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='EVAL_METRIC' AND xtype='U')
CREATE TABLE EVAL_METRIC (
    F_ID               BIGINT NOT NULL PRIMARY KEY,
    F_METRIC_CODE      NVARCHAR(50) NOT NULL,
    F_METRIC_NAME      NVARCHAR(100) NOT NULL,
    F_METRIC_TYPE      NVARCHAR(20) NOT NULL,
    F_THRESHOLD_WARN   DECIMAL(10,4) NULL,
    F_THRESHOLD_CRIT   DECIMAL(10,4) NULL,
    F_UNIT             NVARCHAR(20) NULL,
    F_DESCRIPTION      NVARCHAR(500) NULL,
    F_TENANT_ID        NVARCHAR(50) NOT NULL DEFAULT 'default',
    F_CREATOR_USER_ID  NVARCHAR(50) NULL,
    F_CREATOR_TIME     DATETIME NULL,
    F_LAST_MODIFY_USER_ID NVARCHAR(50) NULL,
    F_LAST_MODIFY_TIME    DATETIME NULL
);

-- ==================== 7. 知识图谱表字段补充（表可能已存在）====================
IF EXISTS (SELECT * FROM sysobjects WHERE name='BASE_KNOWLEDGE_NODE' AND xtype='U')
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id=OBJECT_ID('BASE_KNOWLEDGE_NODE') AND name='F_VERSION')
        ALTER TABLE BASE_KNOWLEDGE_NODE ADD F_VERSION INT NOT NULL DEFAULT 0;
END

IF EXISTS (SELECT * FROM sysobjects WHERE name='BASE_KNOWLEDGE_EDGE' AND xtype='U')
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id=OBJECT_ID('BASE_KNOWLEDGE_EDGE') AND name='F_VERSION')
        ALTER TABLE BASE_KNOWLEDGE_EDGE ADD F_VERSION INT NOT NULL DEFAULT 0;
END

-- ==================== 8. BASE_USER 密码字段扩展 ====================
IF EXISTS (SELECT * FROM sys.columns WHERE object_id=OBJECT_ID('BASE_USER') AND name='F_PASSWORD')
    ALTER TABLE BASE_USER ALTER COLUMN F_PASSWORD NVARCHAR(255) NULL;

-- ==================== 9. 全部索引 ====================
CREATE INDEX IDX_STALE_CHECK ON BASE_AI_PIPELINE(F_STAGE_STATUS, F_LAST_MODIFY_TIME, F_CURRENT_STAGE);
CREATE INDEX IDX_IR_VERSION_QUERY ON BASE_IR_VERSION(F_PIPELINE_ID, F_SNAPSHOT_AT DESC);
CREATE INDEX IDX_IR_VERSION_CLEANUP ON BASE_IR_VERSION(F_PIPELINE_ID, F_CHANGE_TYPE, F_SNAPSHOT_AT);
CREATE INDEX IDX_IR_VERSION_TREE ON BASE_IR_VERSION(F_PIPELINE_ID, F_PARENT_VERSION_ID);
CREATE INDEX IDX_EDIT_PATCH_PIPELINE ON BASE_IR_EDIT_PATCH(F_PIPELINE_ID, F_STATUS);
CREATE INDEX IDX_PIPELINE_MSG_QUERY ON BASE_AI_PIPELINE_MESSAGE(F_PIPELINE_ID, F_STAGE, F_CREATOR_TIME DESC);
CREATE INDEX IDX_AI_CALL_LOG_QUERY ON BASE_AI_CALL_LOG(F_TENANT_ID, F_CREATOR_TIME DESC, F_PROVIDER);
CREATE INDEX IDX_EDIT_PATCH_STATUS ON BASE_IR_EDIT_PATCH(F_PIPELINE_ID, F_STATUS, F_CREATOR_TIME DESC);

-- ==================== 验证 SQL ====================
PRINT '=== DDL 初始化完成 ===';
