-- ========================================
-- 裁决书-议题1：状态机与流程 DDL 变更
-- 日期：2026-06-20
-- ========================================

-- 1. BASE_AI_PIPELINE 新增字段
ALTER TABLE BASE_AI_PIPELINE ADD F_VALIDATION_ID NVARCHAR(50) NULL;
ALTER TABLE BASE_AI_PIPELINE ADD F_STALE_FROM_STAGE NVARCHAR(50) NULL;
ALTER TABLE BASE_AI_PIPELINE ADD F_REJECT_COUNT INT NOT NULL DEFAULT 0;
ALTER TABLE BASE_AI_PIPELINE ADD F_ABANDONED_AT DATETIME NULL;
ALTER TABLE BASE_AI_PIPELINE ADD F_ABANDONED_BY NVARCHAR(50) NULL;
ALTER TABLE BASE_AI_PIPELINE ADD F_ABANDON_REASON NVARCHAR(500) NULL;
ALTER TABLE BASE_AI_PIPELINE ADD F_STALE_SINCE DATETIME NULL;

-- 2. BASE_IR_VERSION 新建表
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='BASE_IR_VERSION' AND xtype='U')
BEGIN
    CREATE TABLE BASE_IR_VERSION (
        F_ID NVARCHAR(50) PRIMARY KEY,
        F_PIPELINE_ID NVARCHAR(50) NOT NULL,
        F_VERSION INT NOT NULL,
        F_TRIGGERED_BY NVARCHAR(100) NULL,
        F_CHANGE_SUMMARY NVARCHAR(500) NULL,
        F_PARENT_VERSION INT NULL,
        F_DIFF NVARCHAR(MAX) NULL,
        F_IR_SNAPSHOT NVARCHAR(MAX) NULL,
        F_CREATOR_TIME DATETIME NULL,
        F_CREATOR_USER_ID NVARCHAR(50) NULL,
        F_LAST_MODIFY_TIME DATETIME NULL,
        F_LAST_MODIFY_USER_ID NVARCHAR(50) NULL,
        F_DELETE_MARK INT NULL DEFAULT 0,
        F_DELETE_TIME DATETIME NULL,
        F_DELETE_USER_ID NVARCHAR(50) NULL,
        F_SORT_CODE BIGINT NULL,
        F_ENABLED_MARK INT NULL DEFAULT 1,
        F_TENANT_ID NVARCHAR(50) NULL
    );
END

-- 3. 复合索引（StaleMonitorService 查询优化）
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IDX_STALE_CHECK' AND object_id = OBJECT_ID('BASE_AI_PIPELINE'))
BEGIN
    CREATE INDEX IDX_STALE_CHECK
    ON BASE_AI_PIPELINE(F_STAGE_STATUS, F_LAST_MODIFY_TIME, F_CURRENT_STAGE);
END
