-- ========================================
-- 裁决书合并 DDL（议题1 + 议题3）
-- 日期：2026-06-20
-- ========================================

-- ==================== A. BASE_AI_PIPELINE 新增字段 ====================

-- 议题1 字段
ALTER TABLE BASE_AI_PIPELINE ADD F_VALIDATION_ID NVARCHAR(50) NULL;
ALTER TABLE BASE_AI_PIPELINE ADD F_STALE_FROM_STAGE NVARCHAR(50) NULL;
ALTER TABLE BASE_AI_PIPELINE ADD F_REJECT_COUNT INT NOT NULL DEFAULT 0;
ALTER TABLE BASE_AI_PIPELINE ADD F_ABANDONED_AT DATETIME NULL;
ALTER TABLE BASE_AI_PIPELINE ADD F_ABANDONED_BY NVARCHAR(50) NULL;
ALTER TABLE BASE_AI_PIPELINE ADD F_ABANDON_REASON NVARCHAR(500) NULL;
ALTER TABLE BASE_AI_PIPELINE ADD F_STALE_SINCE DATETIME NULL;
ALTER TABLE BASE_AI_PIPELINE ADD F_STAGE_STATUS INT NULL;

-- 议题3 字段
ALTER TABLE BASE_AI_PIPELINE ADD F_FAILURE_COUNTS NVARCHAR(MAX) NULL;  -- JSON失败计数 {llm_timeout:2,compile_failure:0,sandbox_error:0}
ALTER TABLE BASE_AI_PIPELINE ADD F_STALE_AT DATETIME NULL;              -- 进入stale的时间（与F_STALE_SINCE互补）

-- ==================== B. BASE_IR_VERSION 补充字段 ====================

-- 议题1 字段
ALTER TABLE BASE_IR_VERSION ADD F_TRIGGERED_BY NVARCHAR(100) NULL;
ALTER TABLE BASE_IR_VERSION ADD F_CHANGE_SUMMARY NVARCHAR(500) NULL;
ALTER TABLE BASE_IR_VERSION ADD F_PARENT_VERSION_ID BIGINT NULL;
ALTER TABLE BASE_IR_VERSION ADD F_DIFF NVARCHAR(MAX) NULL;

-- 议题3 字段
ALTER TABLE BASE_IR_VERSION ADD F_CHANGE_TYPE NVARCHAR(20) NULL;          -- full_rollback/surgical_edit/stage_advance
ALTER TABLE BASE_IR_VERSION ADD F_EDIT_PATCH_ID BIGINT NULL;              -- 关联编辑补丁ID
ALTER TABLE BASE_IR_VERSION ADD F_VALIDATION_RESULT NVARCHAR(MAX) NULL;   -- 校验链结果JSON
ALTER TABLE BASE_IR_VERSION ADD F_SNAPSHOT_AT DATETIME NULL;              -- 快照时间

-- F_DIFF 默认值（空JSON数组）
ALTER TABLE BASE_IR_VERSION ADD CONSTRAINT DF_IR_VERSION_DIFF DEFAULT '[]' FOR F_DIFF;

-- ==================== C. 新建表 ====================

-- 分治编辑补丁表 (ARC-3-006)
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='BASE_IR_EDIT_PATCH' AND xtype='U')
BEGIN
    CREATE TABLE BASE_IR_EDIT_PATCH (
        F_ID              BIGINT NOT NULL PRIMARY KEY,
        F_PIPELINE_ID     BIGINT NOT NULL,
        F_VERSION_ID      BIGINT NULL,
        F_TARGET_NODE_IDS NVARCHAR(MAX) NOT NULL,
        F_OPERATIONS      NVARCHAR(MAX) NOT NULL,
        F_EXPLANATION     NVARCHAR(500) NULL,
        F_STATUS          NVARCHAR(20) NOT NULL DEFAULT 'pending',
        F_APPLIED_COUNT   INT NOT NULL DEFAULT 0,
        F_FAILED_COUNT    INT NOT NULL DEFAULT 0,
        F_CHANGE_TYPE     NVARCHAR(20) NOT NULL DEFAULT 'surgical_edit',
        F_TENANT_ID       NVARCHAR(50) NOT NULL DEFAULT 'default',
        F_CREATOR_USER_ID NVARCHAR(50) NULL,
        F_CREATOR_TIME    DATETIME NULL,
        F_LAST_MODIFY_USER_ID NVARCHAR(50) NULL,
        F_LAST_MODIFY_TIME    DATETIME NULL,
        F_DELETE_MARK     INT NULL DEFAULT 0
    );
END

-- ==================== D. 索引 ====================

-- 议题1: StaleMonitorService 查询优化
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IDX_STALE_CHECK' AND object_id = OBJECT_ID('BASE_AI_PIPELINE'))
    CREATE INDEX IDX_STALE_CHECK ON BASE_AI_PIPELINE(F_STAGE_STATUS, F_LAST_MODIFY_TIME, F_CURRENT_STAGE);

-- 议题3: IR版本清理 + 版本树遍历
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IDX_IR_VERSION_CLEANUP' AND object_id = OBJECT_ID('BASE_IR_VERSION'))
    CREATE INDEX IDX_IR_VERSION_CLEANUP ON BASE_IR_VERSION(F_PIPELINE_ID, F_CHANGE_TYPE, F_SNAPSHOT_AT);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IDX_IR_VERSION_TREE' AND object_id = OBJECT_ID('BASE_IR_VERSION'))
    CREATE INDEX IDX_IR_VERSION_TREE ON BASE_IR_VERSION(F_PIPELINE_ID, F_PARENT_VERSION_ID);

-- 编辑补丁查询
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IDX_EDIT_PATCH_PIPELINE' AND object_id = OBJECT_ID('BASE_IR_EDIT_PATCH'))
    CREATE INDEX IDX_EDIT_PATCH_PIPELINE ON BASE_IR_EDIT_PATCH(F_PIPELINE_ID, F_STATUS);
