-- ============================================================
-- 补丁：为 BASE_AI_PIPELINE / BASE_AI_PIPELINE_MESSAGE 补充缺失列
-- 原因：TenantCLDSEntityBase 定义了 F_DELETE_TIME / F_DELETE_USER_ID，
--       但完整初始化脚本建表时遗漏，导致 Insertable/Updateable 报
--       "列名 'F_DELETE_TIME' 无效"
-- 日期：2026-06-18
-- ============================================================

-- BASE_AI_PIPELINE
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BASE_AI_PIPELINE') AND name = 'F_DELETE_TIME')
BEGIN
    ALTER TABLE BASE_AI_PIPELINE ADD F_DELETE_TIME DATETIME NULL;
    PRINT 'BASE_AI_PIPELINE: 已添加 F_DELETE_TIME';
END

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BASE_AI_PIPELINE') AND name = 'F_DELETE_USER_ID')
BEGIN
    ALTER TABLE BASE_AI_PIPELINE ADD F_DELETE_USER_ID NVARCHAR(50) NULL;
    PRINT 'BASE_AI_PIPELINE: 已添加 F_DELETE_USER_ID';
END

-- BASE_AI_PIPELINE_MESSAGE
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BASE_AI_PIPELINE_MESSAGE') AND name = 'F_DELETE_TIME')
BEGIN
    ALTER TABLE BASE_AI_PIPELINE_MESSAGE ADD F_DELETE_TIME DATETIME NULL;
    PRINT 'BASE_AI_PIPELINE_MESSAGE: 已添加 F_DELETE_TIME';
END

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BASE_AI_PIPELINE_MESSAGE') AND name = 'F_DELETE_USER_ID')
BEGIN
    ALTER TABLE BASE_AI_PIPELINE_MESSAGE ADD F_DELETE_USER_ID NVARCHAR(50) NULL;
    PRINT 'BASE_AI_PIPELINE_MESSAGE: 已添加 F_DELETE_USER_ID';
END

GO
