-- ========================================
-- 第四轮第四议题 DDL
-- 日期：2026-06-17
-- 来源：I-05 OTel追踪字段 + I-06 性能基线表
-- ========================================

-- I-05: OTel 追踪字段
ALTER TABLE BASE_AI_CALL_LOG ADD F_TRACE_ID NVARCHAR(50) NULL;
ALTER TABLE BASE_AI_CALL_LOG ADD F_TRACE_SOURCE NVARCHAR(20) NULL;

-- I-06: 性能基线表
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='BENCHMARK_BASELINE' AND xtype='U')
CREATE TABLE BENCHMARK_BASELINE (
    F_ID              BIGINT NOT NULL PRIMARY KEY,
    F_METRIC_CODE     NVARCHAR(50) NOT NULL,
    F_SANDBOX_COUNT   INT NOT NULL,
    F_VALUE           DECIMAL(18,4) NOT NULL,
    F_UNIT            NVARCHAR(20) NOT NULL,
    F_ENVIRONMENT     NVARCHAR(20) NOT NULL,
    F_VERSION         NVARCHAR(20) NOT NULL,
    F_MEASURED_AT     DATETIME NOT NULL,
    F_TENANT_ID       NVARCHAR(50) NOT NULL DEFAULT 'default',
    F_CREATE_TIME     DATETIME NULL,
    F_MODIFY_TIME     DATETIME NULL
);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_BENCHMARK_METRIC')
    CREATE INDEX IDX_BENCHMARK_METRIC ON BENCHMARK_BASELINE(F_METRIC_CODE, F_SANDBOX_COUNT, F_MEASURED_AT DESC);
