<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\..\system\JNPF.Systems.Entitys\JNPF.Systems.Entitys.csproj" />
		<ProjectReference Include="..\..\workflow\JNPF.WorkFlow.Entitys\JNPF.WorkFlow.Entitys.csproj" />
		<ProjectReference Include="..\JNPF.VisualDev.Entitys\JNPF.VisualDev.Entitys.csproj" />
	</ItemGroup>

</Project>
