-- Logging System Overhaul: Add TraceId and TenantId to BASE_SYS_LOG
-- Date: 2026-05-31

ALTER TABLE BASE_SYS_LOG ADD F_TRACE_ID NVARCHAR(64) NULL;
ALTER TABLE BASE_SYS_LOG ADD F_TENANT_ID NVARCHAR(64) NULL;

-- Index for TraceId queries
CREATE NONCLUSTERED INDEX IX_SYS_LOG_TRACE_ID ON BASE_SYS_LOG(F_TRACE_ID);

-- Index for tenant + time range queries
CREATE NONCLUSTERED INDEX IX_SYS_LOG_TENANT_TIME ON BASE_SYS_LOG(F_TENANT_ID, F_CREATOR_TIME);
