<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>JNPF 数据库访问器 SqlSugar 插件。</Description>
		<TargetFrameworks>net6.0</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Models\IIgnoreSystemFilter.cs" />
	</ItemGroup>
	
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="SqlSugarCore" Version="5.1.4.140" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net5.0' ">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net7.0' ">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\JNPF\JNPF.csproj" />
	</ItemGroup>

</Project>
